using System;
using System.Collections;
using HarmonyLib;
using LevelGeneration;
using MakerGraphTool;
using MakerGraphTool.Nodes;
using PerfectRandom.Sulfur.Core.LevelGeneration;
using ILogger = FalseGods.RuntimeContracts.Diagnostics.ILogger;

namespace FalseGods.Integration.Sulfur.Arena
{
    /// <summary>
    /// The Strategy A hooks into SULFUR's level generation: they observe every generation step of a hijacked load
    /// and skip the ones our single-room arena replaces. This is the first — and so far only — place in the
    /// project that patches the base game (FG-ARCH-006 makes this assembly the only one that may).
    /// </summary>
    /// <remarks>
    /// <para><b>Where the seam is, and why it is not a coroutine problem.</b> A level is generated by a graph of
    /// <see cref="MakerNodeBase"/> steps, and <c>RunnerNode</c> drives every one of them through
    /// <c>MakerNodeBase.StartExecution</c>. That method is an <i>ordinary</i> method that happens to <i>return</i>
    /// an <see cref="IEnumerator"/> — it is not itself an iterator — so a prefix can substitute the enumerator
    /// wholesale without ever touching a compiler-generated state machine. The game already does exactly this for
    /// a step switched off in the editor (<c>if (Run.Disabled) return DummyRunner();</c>); a skip here takes the
    /// same path, including its bookkeeping, so the loading progress count stays honest.</para>
    /// <para><b>Scope.</b> Both hooks do nothing at all unless <see cref="LevelGenerationHijack.IsArmed"/> — an
    /// ordinary level the player loads generates completely untouched. The arming is closed out by wrapping
    /// <c>MakerGraphContext.StartMaking</c>, whose completion <i>is</i> "one whole generation run"; the wrapper
    /// disarms in a <c>finally</c>, so a run that throws or is abandoned still releases the hooks.</para>
    /// <para><b>Failure is open, deliberately.</b> If a hook throws, the original step runs. For a development
    /// bring-up the safe failure is an ordinary cave level, not a wedged load.</para>
    /// </remarks>
    public static class LevelGenerationHijackPatches
    {
        private const string HarmonyId = "ryuka_labs.falsegods.levelgen";

        private static bool _installed;

        /// <summary>
        /// Apply the generation hooks once. Called from the Composition Root; safe to call again (a second call is
        /// a no-op). A failure to patch is logged and left alone — the game still loads levels normally, the
        /// hijack simply does not take effect.
        /// </summary>
        public static void Install(ILogger? logger)
        {
            if (_installed)
            {
                return;
            }

            LevelGenerationHijack.Logger = logger;

            try
            {
                var harmony = new Harmony(HarmonyId);

                harmony.Patch(
                    AccessTools.DeclaredMethod(typeof(MakerNodeBase), nameof(MakerNodeBase.StartExecution)),
                    prefix: new HarmonyMethod(AccessTools.DeclaredMethod(
                        typeof(LevelGenerationHijackPatches), nameof(ObserveOrSkipStep))));

                // Execute is an iterator, but a prefix that supplies __result replaces the enumerator the method
                // hands back — the generated state machine is never touched, so there is nothing here that a
                // transpiler's iterator caveats apply to.
                harmony.Patch(
                    AccessTools.DeclaredMethod(typeof(CreateStartAreaNode), "Execute"),
                    prefix: new HarmonyMethod(AccessTools.DeclaredMethod(
                        typeof(LevelGenerationHijackPatches), nameof(PlaceArenaAsStartArea))));

                // Two overloads; the parameterless-target one delegates to this, so patching it covers both.
                harmony.Patch(
                    AccessTools.DeclaredMethod(
                        typeof(MakerGraphContext),
                        nameof(MakerGraphContext.StartMaking),
                        new[] { typeof(MakerNodeBase), typeof(MakerGraphContext.OnNodeExecuting) }),
                    postfix: new HarmonyMethod(AccessTools.DeclaredMethod(
                        typeof(LevelGenerationHijackPatches), nameof(ScopeToOneGenerationRun))));

                _installed = true;
                logger?.Log("[levelgen] generation hooks installed.");
            }
            catch (Exception exception)
            {
                logger?.LogWarning($"[levelgen] generation hooks could not be installed: {exception}");
            }
        }

        /// <summary>
        /// Runs before every generation step of a hijacked load: reports which step is about to run, and replaces
        /// the ones our arena supersedes with a step that does nothing. Returns true to let the original run.
        /// </summary>
        private static bool ObserveOrSkipStep(MakerNodeBase __instance, MakerGraphContext context, ref IEnumerator __result)
        {
            if (!LevelGenerationHijack.IsArmed || __instance == null)
            {
                return true;
            }

            try
            {
                var nodeType = __instance.GetType();
                // StartExecution increments before running, so the step about to run is the next index.
                var step = context != null ? context.ExecutingNodeIndex + 1 : -1;

                if (!LevelGenerationHijack.IsNeutered(nodeType))
                {
                    LevelGenerationHijack.Logger?.Log($"[levelgen] step {step}: {nodeType.Name} (native)");
                    return true;
                }

                if (context == null)
                {
                    // No context to keep books against; leave the step alone rather than half-skip it.
                    LevelGenerationHijack.Logger?.LogWarning(
                        $"[levelgen] {nodeType.Name} has no generation context; leaving it to run.");
                    return true;
                }

                // The game's own "this step is switched off" path: bind the context, count the step, hand back a
                // runner that does nothing.
                __instance.SetContext(context);
                context.ExecutingNodeIndex++;
                __result = SkippedStep();
                LevelGenerationHijack.Logger?.Log($"[levelgen] step {step}: {nodeType.Name} (skipped)");
                return false;
            }
            catch (Exception exception)
            {
                LevelGenerationHijack.Logger?.LogWarning($"[levelgen] step hook threw, running the step: {exception}");
                return true;
            }
        }

        /// <summary>
        /// Wraps one whole generation run so the hijack releases when it ends, however it ends.
        /// </summary>
        private static void ScopeToOneGenerationRun(ref IEnumerator __result)
        {
            if (!LevelGenerationHijack.IsArmed || __result == null)
            {
                return;
            }

            __result = DisarmWhenFinished(__result);
        }

        /// <summary>
        /// Runs in place of the level's own start-area step: puts our arena in the level instead of a vanilla
        /// start room. The arena is acquired here, before the step is taken over, so that content which will not
        /// load costs an ordinary cave level rather than a level with no start area at all.
        /// </summary>
        private static bool PlaceArenaAsStartArea(CreateStartAreaNode __instance, ref IEnumerator __result)
        {
            if (!LevelGenerationHijack.IsArmed || __instance == null)
            {
                return true;
            }

            try
            {
                var rooms = LevelGenerationHijack.ArenaRooms;
                if (rooms == null)
                {
                    LevelGenerationHijack.Logger?.LogWarning(
                        "[levelgen] no arena source installed; generating the level's own start area.");
                    return true;
                }

                // StartExecution has already bound the context and reset the per-step seed before calling us.
                if (!(__instance.Context is LevelGenerationContext context))
                {
                    LevelGenerationHijack.Logger?.LogWarning(
                        "[levelgen] start-area step has no level-generation context; leaving it to generate.");
                    return true;
                }

                var room = rooms.Acquire();
                if (room == null)
                {
                    return true; // the source already reported why
                }

                __result = StartAreaFromArena(__instance, context, room);
                return false;
            }
            catch (Exception exception)
            {
                LevelGenerationHijack.Logger?.LogWarning(
                    $"[levelgen] arena injection threw, generating the level's own start area: {exception}");
                return true;
            }
        }

        /// <summary>
        /// The start-area step, with our arena as the start room: the level's ordered rooms, the player spawn the
        /// rest of generation reads, and a sealed (empty) set of outgoing connectors.
        /// </summary>
        private static IEnumerator StartAreaFromArena(
            CreateStartAreaNode node, LevelGenerationContext context, Room room)
        {
            // Hand the arena to the level's own managed results, so the level that created it also destroys it.
            // Its bundle and borrowed materials stay ours to release (HijackedArenaRoomSource).
            node.AddManagedObject(room.gameObject);

            context.orderedRooms.Clear();
            context.orderedRooms.Add(room);
            context.spawnPoint = room.GetPlayerSpawnPoint(string.Empty);
            context.startOutConnectors = room.gameObject.GetChildConnectorsSorted();

            if (context.spawnPoint == null)
            {
                // The player spawner reads this directly; losing it would be a null dereference three steps later.
                LevelGenerationHijack.Logger?.LogWarning(
                    "[levelgen] the arena room exposes no player spawn point; the level will have nowhere to place the player.");
            }

            LevelGenerationHijack.Logger?.Log("[levelgen] arena placed as the level's start area.");
            yield return null;
        }

        /// <summary>The game's <c>DummyRunner</c>: one frame, no work.</summary>
        private static IEnumerator SkippedStep()
        {
            yield return null;
        }

        /// <summary>Drive the real generation run through, then release the hijack — including on failure, so a
        /// broken load never leaves the hooks armed for the player's next level.</summary>
        private static IEnumerator DisarmWhenFinished(IEnumerator run)
        {
            try
            {
                // Current is forwarded unchanged: the callers treat a yielded IEnumerator as a nested routine.
                while (run.MoveNext())
                {
                    yield return run.Current;
                }
            }
            finally
            {
                LevelGenerationHijack.Logger?.Log("[levelgen] generation run ended; hijack released.");
                LevelGenerationHijack.Disarm();
            }
        }
    }
}
