namespace FalseGods.Application.Arena
{
    /// <summary>
    /// The "load our arena AS the level" seam (Strategy A). Instead of overlaying an additive arena onto a live
    /// level — which fail-closes when that level's navigation is not scanned at the raise site (the Strategy B
    /// limit on a large boss arena) — this drives the game's OWN level load so our cave IS the level. The game then
    /// generates the level, scans navigation, and spawns the player natively, sidestepping the manual rescan.
    /// </summary>
    /// <remarks>
    /// The implementation lives in <c>Integration.Sulfur</c> (which references <c>Application</c>): it calls the
    /// game's level-load entry point for the first cave environment. This is a development trigger for now — the
    /// player-facing entry (a developer-menu button) is a later concern. Loading the level is the game's job; what
    /// content that level contains is decided by a separate generation hook (added incrementally).
    /// </remarks>
    public interface IArenaHijackPort
    {
        /// <summary>Whether this peer is currently declaring the arena level to be the arena.</summary>
        bool IsArenaModeOn { get; }

        /// <summary>
        /// Declare the arena level to be the boss arena on this peer, and load it now through the game's own
        /// level generation (native generation, navigation, and player spawn). The declaration <b>stands</b>
        /// until <see cref="LeaveArenaMode"/>: in a session the level is regenerated by paths this peer does not
        /// initiate — a peer following the host, or the host leading a peer's transition — and each of those must
        /// build the same arena rather than an ordinary cave. A missing game manager is a no-op.
        /// </summary>
        void LoadHijackedArena();

        /// <summary>Stop declaring the arena level to be the arena. The level currently standing is left alone;
        /// the next generation of it is an ordinary one. A no-op when the mode is already off.</summary>
        void LeaveArenaMode();
    }
}
