using FalseGods.Protocol.Wire;

namespace FalseGods.Application.Arena
{
    /// <summary>
    /// The "load our arena AS the level" seam (Strategy A). Instead of overlaying an additive arena onto a live
    /// level — which fail-closes when that level's navigation is not scanned at the raise site (the Strategy B
    /// limit on a large boss arena) — this drives the game's OWN level load so our cave IS the level. The game then
    /// generates the level, scans navigation, and spawns the player natively, sidestepping the manual rescan.
    /// </summary>
    /// <remarks>
    /// The implementation lives in <c>Integration.Sulfur</c> (which references <c>Application</c>): it calls the
    /// game's level-load entry point for the first cave environment. This is a development trigger for now — the
    /// player-facing entry (a developer-menu button) is a later concern. Loading the level is the game's job; what
    /// content that level contains is decided by a separate generation hook (added incrementally).
    /// </remarks>
    public interface IArenaHijackPort
    {
        /// <summary>The level this build's boss arena replaces, in the wire's game-independent terms — what a
        /// session agrees on (<see cref="ArenaLevelFlow"/>).</summary>
        ArenaLevelId ArenaLevel { get; }

        /// <summary>Whether a level is currently declared to be the boss arena on this peer.</summary>
        bool IsArenaModeOn { get; }

        /// <summary>
        /// Declare <paramref name="level"/> to be the boss arena on this peer, without loading anything. The
        /// declaration <b>stands</b>: the level is regenerated by paths this peer does not initiate — following
        /// the host, or the host leading another peer's transition — and each of those must build the arena
        /// rather than the game's own content. An environment this build does not recognise is refused, not
        /// cast: the value arrives over the wire.
        /// </summary>
        /// <returns>Whether the level was accepted.</returns>
        bool DeclareArenaLevel(ArenaLevelId level);

        /// <summary>Stop declaring any level to be the boss arena. The level currently standing is left alone;
        /// the next generation of it is an ordinary one. A no-op when nothing is declared.</summary>
        void LeaveArenaMode();

        /// <summary>Go to the boss arena now, through the game's own level generation (native generation,
        /// navigation, and player spawn) — also how re-authored arena content is picked up. Declares
        /// <see cref="ArenaLevel"/> first, so it works whether or not it was declared already. A missing game
        /// manager is a no-op.</summary>
        void LoadHijackedArena();
    }
}
