<#
.SYNOPSIS
    Push the current branch and open or update a normal pull request, then wait for the required CI check.

.DESCRIPTION
    The task is already finished, committed, and verified. The caller supplies an accurate English title and a
    body file (built from the real diff, commits, and verification output). This script does the mechanical,
    safety-sensitive part:

      1. Preflight — this is the False Gods repo, git and gh are present and authenticated, HEAD is a real
         branch (not master, not detached), the working tree is clean, and the body carries the three required
         headings.
      2. Push the branch with upstream tracking. The existing pre-push hook runs the full Debug+Release verify;
         this script never passes --no-verify and never bypasses it.
      3. Open a normal PR (base master, not a draft) for this head branch, or update the existing open one.
         One PR per branch — it never creates a duplicate.
      4. Wait for the required `verify` check. CI failure or timeout leaves the PR in place and exits non-zero;
         only a passing check exits 0. The real PR URL is printed either way.

    What this script deliberately never does: merge (no `gh pr merge`), bypass branch protection or a ruleset,
    use admin override, generate the title/body itself, or print/manage tokens or credentials. The final merge
    is a maintainer's manual click on GitHub.

    Windows PowerShell 5.1. Native commands are judged ONLY by their exit code, never by scraping their text
    (this repo's own build prints "0 个错误" on success, so grepping for "error" is actively wrong). Every git
    and gh call is invoked with an argument array, never by building a shell string, so paths and text with
    spaces or non-ASCII characters pass through intact.

.PARAMETER Title
    The PR title. English, accurate, generated by the caller from the real change.

.PARAMETER BodyFile
    Path to a UTF-8 file holding the PR body. Must contain the headings Summary, Verification, and
    Scope / limitations (the repository PR template).

.PARAMETER BaseBranch
    The PR base branch. Default: master.

.PARAMETER Remote
    The git remote to push to and resolve the GitHub repo from. Default: origin.

.PARAMETER TimeoutSeconds
    How long to wait for the required `verify` check to finish. Default: 1800 (30 min).

.PARAMETER PollSeconds
    Interval between check-status polls. Default: 15.

.EXAMPLE
    .\scripts\submit-pr.ps1 `
        -Title "Add project PR submission workflow" `
        -BodyFile "$env:TEMP\false-gods-pr.md"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $Title,
    [Parameter(Mandatory)] [string] $BodyFile,
    [string] $BaseBranch = 'master',
    [string] $Remote = 'origin',
    [int]    $TimeoutSeconds = 1800,
    [int]    $PollSeconds = 15
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot

# The required GitHub status-check context this repo gates merges on (see .github/workflows/verify.yml).
$RequiredCheckName = 'verify'

function Stop-WithError {
    param([string] $Message)
    Write-Host ''
    Write-Host "submit-pr: $Message" -ForegroundColor Red
    exit 1
}

<#
    Run a native command and return its exit code plus captured stdout, without letting native stderr or the
    caller's redirection decide the verdict. In Windows PowerShell 5.1 a native command's stderr becomes
    ErrorRecords under $ErrorActionPreference='Stop', which would abort the script on harmless advisories
    (git in particular writes plenty). So stderr is forced to Continue for the duration and redirected to a
    temp file, keeping stdout clean for JSON parsing. Success/failure is the exit code alone.
#>
function Invoke-Native {
    param([Parameter(Mandatory)] [scriptblock] $Command)

    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $errFile = [System.IO.Path]::GetTempFileName()
    try {
        $out = & $Command 2> $errFile
        $code = $LASTEXITCODE
        $err = ''
        if (Test-Path -LiteralPath $errFile) {
            $err = [System.IO.File]::ReadAllText($errFile)
        }
    }
    finally {
        $ErrorActionPreference = $previous
        Remove-Item -LiteralPath $errFile -ErrorAction SilentlyContinue
    }

    [pscustomobject]@{
        ExitCode = $code
        StdOut   = ($out | Out-String)
        StdErr   = $err
    }
}

# Identify a statusCheckRollup entry: GitHub Actions check runs carry 'name', legacy commit statuses carry
# 'context'. Property existence is probed via PSObject so Set-StrictMode does not throw on the absent one.
function Get-CheckName {
    param($Entry)
    if ($Entry.PSObject.Properties['name'] -and $Entry.name)       { return [string]$Entry.name }
    if ($Entry.PSObject.Properties['context'] -and $Entry.context) { return [string]$Entry.context }
    return ''
}

# Classify one statusCheckRollup entry as pass / pending / fail / error, with a readable state string. A check run
# reports 'status' (+ 'conclusion' once completed); a legacy status reports 'state'. Only an explicit success
# is a pass; any other terminal state is a failure; anything not yet terminal is pending.
function Get-CheckVerdict {
    param($Entry)

    if ($Entry.PSObject.Properties['status']) {
        $status = if ($Entry.status) { ([string]$Entry.status).ToUpperInvariant() } else { '' }
        if ($status -ne 'COMPLETED') { return [pscustomobject]@{ Verdict = 'pending'; State = $status } }
        $conclusion = if ($Entry.PSObject.Properties['conclusion'] -and $Entry.conclusion) { ([string]$Entry.conclusion).ToUpperInvariant() } else { '' }
        if ($conclusion -eq 'SUCCESS') { return [pscustomobject]@{ Verdict = 'pass'; State = $conclusion } }
        return [pscustomobject]@{ Verdict = 'fail'; State = $conclusion }
    }

    if ($Entry.PSObject.Properties['state']) {
        $state = if ($Entry.state) { ([string]$Entry.state).ToUpperInvariant() } else { '' }
        if ($state -eq 'SUCCESS') { return [pscustomobject]@{ Verdict = 'pass'; State = $state } }
        if ($state -eq 'PENDING' -or $state -eq 'EXPECTED') { return [pscustomobject]@{ Verdict = 'pending'; State = $state } }
        return [pscustomobject]@{ Verdict = 'fail'; State = $state }
    }

    # A named check with neither shape means the response schema is not one we know how to evaluate.
    # Fail immediately instead of disguising that error as a pending check until the timeout.
    return [pscustomobject]@{ Verdict = 'error'; State = 'UNKNOWN_STATUS_SHAPE' }
}

# ------------------------------------------------------------------ preflight
Push-Location $repoRoot
try {
    Write-Host '[1/4] Preflight' -ForegroundColor Cyan

    # Timing parameters must be positive, or the wait loop below is meaningless.
    if ($TimeoutSeconds -le 0) { Stop-WithError "-TimeoutSeconds must be greater than zero (got $TimeoutSeconds)." }
    if ($PollSeconds -le 0)    { Stop-WithError "-PollSeconds must be greater than zero (got $PollSeconds)." }

    # git and gh must both exist on PATH.
    foreach ($tool in @('git', 'gh')) {
        if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
            Stop-WithError "'$tool' is not available on PATH. Install it and try again."
        }
    }

    # This must be a git working tree, and specifically THIS repo — not a parent or nested one that happens to
    # contain the script. Compare the git root against the repo root derived from the script's own location.
    $top = Invoke-Native { & git rev-parse --show-toplevel }
    if ($top.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($top.StdOut)) {
        Stop-WithError "not a git repository. Run this from inside the False Gods clone."
    }
    $gitRoot  = [System.IO.Path]::GetFullPath($top.StdOut.Trim()).TrimEnd('\', '/')
    $thisRoot = [System.IO.Path]::GetFullPath($repoRoot).TrimEnd('\', '/')
    if (-not [string]::Equals($gitRoot, $thisRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        Stop-WithError ("the git root is not the False Gods repo root." + [Environment]::NewLine +
                        "  git root:  $gitRoot" + [Environment]::NewLine +
                        "  this repo: $thisRoot")
    }

    # gh must be authenticated. Judge by exit code; do not print or inspect any token.
    $auth = Invoke-Native { & gh auth status }
    if ($auth.ExitCode -ne 0) {
        Stop-WithError "gh is not authenticated. Run 'gh auth login' first (this script never handles tokens)."
    }

    # HEAD must be a real branch: symbolic-ref fails on a detached HEAD.
    $head = Invoke-Native { & git symbolic-ref --quiet --short HEAD }
    if ($head.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($head.StdOut)) {
        Stop-WithError "HEAD is detached. Check out a feature branch before submitting a PR."
    }
    $branch = $head.StdOut.Trim()

    if ([string]::Equals($branch, $BaseBranch, [System.StringComparison]::OrdinalIgnoreCase)) {
        Stop-WithError "current branch is '$branch', the base branch. Do your work on a feature branch, not '$BaseBranch'."
    }
    if ([string]::Equals($branch, 'master', [System.StringComparison]::OrdinalIgnoreCase)) {
        Stop-WithError "refusing to submit from 'master'. Use a feature branch."
    }

    # Clean working tree — an empty --porcelain listing. (Reading the listing is not judging a command by its
    # text: --porcelain is a stable machine format, and success is still the exit code below.)
    $status = Invoke-Native { & git status --porcelain }
    if ($status.ExitCode -ne 0) {
        Stop-WithError "git status failed (exit $($status.ExitCode))."
    }
    if (-not [string]::IsNullOrWhiteSpace($status.StdOut)) {
        Stop-WithError ("the working tree is not clean. Commit or stash first:" + [Environment]::NewLine +
                        $status.StdOut.TrimEnd())
    }

    # Title must be real text.
    if ([string]::IsNullOrWhiteSpace($Title)) {
        Stop-WithError "-Title is empty."
    }

    # Body file must exist and be non-empty, and carry the three required headings. Read as UTF-8 so non-ASCII
    # bodies survive.
    if (-not (Test-Path -LiteralPath $BodyFile -PathType Leaf)) {
        Stop-WithError "-BodyFile not found: $BodyFile"
    }
    $body = [System.IO.File]::ReadAllText((Resolve-Path -LiteralPath $BodyFile).ProviderPath, [System.Text.Encoding]::UTF8)
    if ([string]::IsNullOrWhiteSpace($body)) {
        Stop-WithError "-BodyFile is empty: $BodyFile"
    }
    $requiredHeadings = @(
        @{ Name = 'Summary';              Pattern = '(?im)^\s{0,3}#{1,6}\s+Summary\s*$' },
        @{ Name = 'Verification';         Pattern = '(?im)^\s{0,3}#{1,6}\s+Verification\s*$' },
        @{ Name = 'Scope / limitations';  Pattern = '(?im)^\s{0,3}#{1,6}\s+Scope\s*/\s*limitations\s*$' }
    )
    $missing = @()
    foreach ($h in $requiredHeadings) {
        if ($body -notmatch $h.Pattern) { $missing += $h.Name }
    }
    if ($missing.Count -gt 0) {
        Stop-WithError ("the PR body is missing required heading(s): {0}. " -f ($missing -join ', ') +
                        "Follow .github/pull_request_template.md (Summary / Verification / Scope / limitations).")
    }

    # Resolve owner/repo from the chosen remote so every gh call targets it explicitly (honours -Remote and
    # avoids gh guessing when several remotes exist). Handles https, git@ and ssh:// forms.
    $remoteUrl = Invoke-Native { & git remote get-url $Remote }
    if ($remoteUrl.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($remoteUrl.StdOut)) {
        Stop-WithError "remote '$Remote' has no URL. Check 'git remote -v'."
    }
    if ($remoteUrl.StdOut.Trim() -match 'github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?\s*$') {
        $ownerRepo = "$($Matches[1])/$($Matches[2])"
    }
    else {
        Stop-WithError "could not parse a GitHub owner/repo from remote '$Remote' ($($remoteUrl.StdOut.Trim()))."
    }

    # The pre-push hook is what runs the full Debug + Release verify on push. If this clone was not set up, the
    # push would skip that verification silently, which defeats the point of submitting through this script.
    # Refuse rather than push unverified.
    $hooksPath = Invoke-Native { & git config --local --get core.hooksPath }
    if ($hooksPath.ExitCode -ne 0 -or $hooksPath.StdOut.Trim() -ne '.githooks') {
        Stop-WithError "core.hooksPath is not '.githooks', so the pre-push verify would not run. Run scripts/setup-dev.ps1 first (once per clone)."
    }

    Write-Host "  repo   $ownerRepo"
    Write-Host "  branch $branch  ->  base $BaseBranch"

    # ------------------------------------------------------------------ push
    Write-Host ''
    Write-Host '[2/4] Push (pre-push hook runs the full Debug + Release verify)' -ForegroundColor Cyan

    # Let the hook's output stream live to the console; judge only by exit code. No --no-verify, ever.
    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    & git push --set-upstream $Remote HEAD
    $pushCode = $LASTEXITCODE
    $ErrorActionPreference = $previous
    if ($pushCode -ne 0) {
        Stop-WithError "git push failed (exit $pushCode). The pre-push verification may have failed; nothing was submitted."
    }

    # ------------------------------------------------------------------ create or update PR
    Write-Host ''
    Write-Host '[3/4] Create or update the pull request' -ForegroundColor Cyan

    $existing = Invoke-Native {
        & gh pr list --repo $ownerRepo --head $branch --state open --json number,url,baseRefName
    }
    if ($existing.ExitCode -ne 0) {
        Stop-WithError ("gh pr list failed (exit $($existing.ExitCode)):" + [Environment]::NewLine + $existing.StdErr.Trim())
    }
    # Windows PowerShell 5.1 hands a JSON array to the pipeline as ONE object rather than enumerating it, so
    # `@(<string> | ConvertFrom-Json)` on an empty result `[]` produces a ONE-element array whose element is an
    # empty Object[] - not an empty array. Assign first, then normalise, then keep only real PR records: an
    # entry with no 'number' is not a pull request and must never reach $openPrs[0].number.
    $openPrs = @()
    if (-not [string]::IsNullOrWhiteSpace($existing.StdOut)) {
        try {
            $parsedPrs = $existing.StdOut | ConvertFrom-Json
        }
        catch {
            Stop-WithError ("gh pr list did not return valid JSON:" + [Environment]::NewLine + $existing.StdOut.Trim())
        }
        if ($null -ne $parsedPrs) {
            $openPrs = @(@($parsedPrs) | Where-Object { $null -ne $_ -and $_.PSObject.Properties['number'] })
        }
    }

    if ($openPrs.Count -gt 0) {
        $prNumber = $openPrs[0].number

        # The open PR for this branch must target the base we were asked to submit against. Retargeting a PR's
        # base is a decision for a human, not a silent side effect of updating its title/body.
        $existingBase = ''
        if ($openPrs[0].PSObject.Properties['baseRefName'] -and $openPrs[0].baseRefName) {
            $existingBase = [string]$openPrs[0].baseRefName
        }
        if (-not [string]::Equals($existingBase, $BaseBranch, [System.StringComparison]::OrdinalIgnoreCase)) {
            Stop-WithError ("open PR #$prNumber targets base '$existingBase', not '$BaseBranch'. " +
                            "Resolve this on GitHub before resubmitting; this script will not change a PR's base.")
        }

        Write-Host "  updating existing PR #$prNumber"
        $edit = Invoke-Native {
            & gh pr edit $prNumber --repo $ownerRepo --title $Title --body-file $BodyFile
        }
        if ($edit.ExitCode -ne 0) {
            Stop-WithError ("gh pr edit failed (exit $($edit.ExitCode)):" + [Environment]::NewLine + $edit.StdErr.Trim())
        }
    }
    else {
        Write-Host "  creating a new PR"
        $create = Invoke-Native {
            & gh pr create --repo $ownerRepo --base $BaseBranch --head $branch --title $Title --body-file $BodyFile
        }
        if ($create.ExitCode -ne 0) {
            Stop-WithError ("gh pr create failed (exit $($create.ExitCode)):" + [Environment]::NewLine + $create.StdErr.Trim())
        }
    }

    # Read back the canonical number + URL rather than trusting create's stdout.
    $view = Invoke-Native {
        & gh pr view --repo $ownerRepo $branch --json number,url
    }
    if ($view.ExitCode -ne 0) {
        Stop-WithError ("gh pr view failed (exit $($view.ExitCode)):" + [Environment]::NewLine + $view.StdErr.Trim())
    }
    $pr = $null
    if (-not [string]::IsNullOrWhiteSpace($view.StdOut)) {
        try { $pr = $view.StdOut | ConvertFrom-Json } catch { $pr = $null }
    }
    if ($null -eq $pr -or -not $pr.PSObject.Properties['number'] -or -not $pr.PSObject.Properties['url']) {
        Stop-WithError ("gh pr view did not return the PR number and URL:" + [Environment]::NewLine + $view.StdOut.Trim())
    }
    $prNumber = $pr.number
    $prUrl = $pr.url
    Write-Host "  PR #$prNumber  $prUrl"

    # ------------------------------------------------------------------ wait for required check
    Write-Host ''
    Write-Host "[4/4] Wait for the required '$RequiredCheckName' check (timeout ${TimeoutSeconds}s)" -ForegroundColor Cyan

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $verdict = 'timeout'
    $verdictDetail = ''

    while ((Get-Date) -lt $deadline) {
        # Read the PR's combined check status with gh pr view --json statusCheckRollup (a supported, read-only
        # command). The distinction that matters: a genuine command failure (authentication, network, or
        # permission) is a non-zero exit and is treated as a hard error here, NOT as "still pending". Only a
        # SUCCESSFUL call whose rollup does not yet contain the required check counts as "not registered yet".
        # That stops a real error from masquerading as a pending check and hanging until the timeout.
        $statusResult = Invoke-Native {
            & gh pr view $branch --repo $ownerRepo --json statusCheckRollup
        }
        if ($statusResult.ExitCode -ne 0) {
            $verdict = 'error'
            $verdictDetail = "gh pr view failed (exit $($statusResult.ExitCode)): $($statusResult.StdErr.Trim())"
            break
        }

        $rollup = @()
        if (-not [string]::IsNullOrWhiteSpace($statusResult.StdOut)) {
            try {
                $data = $statusResult.StdOut | ConvertFrom-Json
            }
            catch {
                $verdict = 'error'
                $verdictDetail = 'could not parse status JSON from gh pr view.'
                break
            }
            if ($null -ne $data -and $data.PSObject.Properties['statusCheckRollup'] -and $null -ne $data.statusCheckRollup) {
                $rollup = @($data.statusCheckRollup)
            }
        }

        $verify = @($rollup | Where-Object { (Get-CheckName $_) -eq $RequiredCheckName })
        if ($verify.Count -eq 0) {
            # Command succeeded, but the required check is not in the rollup yet. This is the only case that
            # legitimately means "not registered" and keeps us waiting.
            Write-Host "  waiting for '$RequiredCheckName' to register..."
            Start-Sleep -Seconds $PollSeconds
            continue
        }

        # Aggregate across any reruns/rows for the required check: any failure fails; otherwise any
        # not-yet-terminal state keeps waiting; only an all-success result passes.
        $states = @($verify | ForEach-Object { Get-CheckVerdict $_ })
        $errors = @($states | Where-Object { $_.Verdict -eq 'error' })
        $failed = @($states | Where-Object { $_.Verdict -eq 'fail' })
        $pending = @($states | Where-Object { $_.Verdict -eq 'pending' })

        if ($errors.Count -gt 0) {
            $verdict = 'error'
            $verdictDetail = "unrecognized '$RequiredCheckName' status data ($($errors[0].State))."
            break
        }
        if ($failed.Count -gt 0) {
            $verdict = 'fail'
            $verdictDetail = $failed[0].State
            break
        }
        if ($pending.Count -gt 0) {
            Write-Host "  '$RequiredCheckName' is $($pending[0].State)..."
            Start-Sleep -Seconds $PollSeconds
            continue
        }

        $verdict = 'pass'
        break
    }

    # ------------------------------------------------------------------ report - URL always, exit code = verdict
    Write-Host ''
    Write-Host "PR: $prUrl"

    if ($verdict -eq 'pass') {
        Write-Host "submit-pr: '$RequiredCheckName' passed. Ready for a maintainer to merge manually on GitHub." -ForegroundColor Green
        exit 0
    }
    elseif ($verdict -eq 'timeout') {
        Write-Host "submit-pr: timed out after ${TimeoutSeconds}s waiting for '$RequiredCheckName'. The PR is open; check it on GitHub." -ForegroundColor Red
        exit 1
    }
    elseif ($verdict -eq 'error') {
        Write-Host "submit-pr: could not determine the '$RequiredCheckName' status: $verdictDetail" -ForegroundColor Red
        Write-Host "submit-pr: the PR is open; re-check it on GitHub. It was not merged." -ForegroundColor Red
        exit 1
    }
    else {
        Write-Host "submit-pr: '$RequiredCheckName' did not pass ($verdictDetail). The PR is left open for you to fix; it was not merged." -ForegroundColor Red
        exit 1
    }
}
finally {
    Pop-Location
}
